FROM node:12.0-alpine
RUN apk add --no-cache bash
WORKDIR /www

ENV PATH /www/node_modules/.bin:$PATH

COPY package.json /www
RUN npm config set unsafe-perm true
RUN npm install
RUN npm install react-scripts@3.0.1 -g --silent

CMD ["env-cmd", "-f", ".env.local", "npm", "start"]